FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=${JAVA_OPTS}
#ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
COPY target/costcontroller-0.0.1-SNAPSHOT.war costcontroller.war
EXPOSE 8080
EXPOSE 5005
CMD ["java", "-war", "costcontroller.war"]